Repository Time-Attendance/time-attendance-front, pull requests merged in 2023-09, with the labels that each got.

#14 [Fix] 변수명 변경
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: ⚒️refactor

#15 [Feat] 회사 설정 페이지 작성
  src/layouts/dashboard/nav/config.js
  src/pages/admin/company/CompanyList.js
  src/pages/admin/company/CompanyListSearchbar.js
  src/pages/admin/company/NewCompanyModal.js
  src/pages/company/CompanySettingPage.js
  src/routes.js
Labels: 🌟feature

#16 [Fix] 회사 로고가 없을 경우 미리보기가 안되는 현상 수정
  src/pages/company/CompanySettingPage.js
Labels: 🐛bug

#17 [Refactor] 사용자 정보를 상태로 관리하도록 수정
  src/api/loginAxios.js
  src/context/AuthProvider.js
  src/layouts/dashboard/nav/index.js
  src/pages/login/LoginForm.js
Labels: ⚒️refactor

#18 [Fix] 날짜 형식으로 인해 오류나던 부분 수정
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: 🐛bug

#23 Schedule
  src/pages/privilege/PrivilegeAdd.js
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: ⚒️refactor

#25 [Feat] 마이페이지 작성
  src/App.js
  src/_mock/mypage.js
  src/components/chart/useChart.js
  src/layouts/dashboard/nav/config.js
  src/pages/login/LoginForm.js
  src/pages/login/LoginPage.js
  src/pages/mypage/AttendanceWidgetSummary.js
  src/pages/mypage/MyPage.js
  src/pages/mypage/TimeRecordList.js
  src/pages/mypage/WeeklyWorkChart.js
  src/pages/mypage/WorkGroupInfo.js
  src/pages/signup/SignupForm.js
  src/routes.js
  src/utils/formatTime.js
Labels: 🌟feature

#34 [Fix] 정산 종합 수정
  src/layouts/dashboard/DashboardLayout.js
  src/pages/privilege/PrivilegeAdd.js
  src/pages/schedule/Calendar.js
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
  src/sections/@dashboard/settlement/SettleListToolbar.js
  src/sections/@dashboard/user/UserListToolbar.js
Labels: ⚒️refactor

#38 [Feat] 권한 파일 수정
  src/pages/privilege/Privilege.css
  src/pages/privilege/PrivilegeAdd.js
  src/pages/schedule/ScheduleModal.js
  src/sections/@dashboard/user/UserListToolbar.js
Labels: 🌟feature

#40 [Feat] 정산 로직 수정
  src/pages/privilege/Privilege.css
  src/pages/privilege/PrivilegeAdd.js
  src/pages/schedule/Calendar.js
  src/pages/schedule/Schedule.css
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: 🌟feature

#46 [Fix] 정산 로직 수정
  src/pages/privilege/PrivilegeAdd.js
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: 🌟feature

#48 [Fix] SweetAlert 정보 수정
  src/pages/privilege/PrivilegeAdd.js
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: ⚒️refactor

#50 [Fix] 정산 페이지 수정
  src/pages/schedule/ScheduleModal.js
  src/pages/schedule/SchedulePage.js
Labels: 🌟feature

#52 [Fix] 권한 수정
  src/pages/privilege/PrivilegeAdd.js
Labels: ⚒️refactor
